name: civic_1
<<<<<<< Updated upstream
description: 'A new Flutter project.'
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
=======
description: "A new Flutter project."
>>>>>>> Stashed changes

# This line prevents accidental publishing to pub.dev.
publish_to: "none"

# Version number and build number for the app.
version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

<<<<<<< Updated upstream
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
=======
  # Common Flutter and Dart dependencies.
>>>>>>> Stashed changes
  cupertino_icons: ^1.0.6
  flutter_switch: ^0.3.2
  toggle_switch: ^2.3.0
  google_fonts: ^6.2.1
  intl: ^0.19.0

  # Firebase and Google Maps dependencies.
  firebase_auth: ^5.3.1
  firebase_storage: ^12.3.2
  cloud_firestore: ^5.4.4
  firebase_core: ^3.6.0
<<<<<<< Updated upstream

  geocoding: ^3.0.0

=======
  google_maps_flutter: ^2.9.0
  geolocator: ^13.0.1
>>>>>>> Stashed changes
  url_launcher: ^6.3.1
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0

  # Other map-related and utility packages.
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  image_picker: ^1.1.2

  # Mailer dependency for sending emails.
  mailer: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended linting rules.
  flutter_lints: ^3.0.0

flutter:
<<<<<<< Updated upstream
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
=======
  # Ensures Material Icons are included.
>>>>>>> Stashed changes
  uses-material-design: true

  # Add image assets here.
  assets:
    - assets/googles.png
<<<<<<< Updated upstream
    - assets/default_event_image.jpg
  #   - images/a_dot_ham.jpeg
=======
>>>>>>> Stashed changes

  # If you need to add custom fonts, you can do so as follows:
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
  #       - asset: fonts/CustomFont-Bold.ttf
  #         weight: 700
